/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getString(memId: string): string
export function setString(memId: string, jsString: string): void
export function init(memId: string, maxSize: number): void
export function clear(memId: string): void
export function setBuffer(memId: string, jsBuffer: Buffer): void
export function getBuffer(memId: string): Buffer
